### ISSUE TITLE
请问一下 3rd session 要在每个业务接口处判断吗？ 有更好的解决方案吗？

### ISSUE THREAD

**Issue by 5046312** [hiscc/panda-chat-room#1]
请问一下 3rd session 要在每个业务接口处判断吗？ 有更好的解决方案吗？

**Comment by hiscc** [comment]
需要保持会话的时候就必须要判断，因为小程序端的 session 和服务器 session 过期时间不一致而且小程序端 session 无法控制失效时间。目前来说需要小程序做判断来更新 session
